-- MATCH INDEX V15.4 LIVE SERVER
-- Run this entire file once in Supabase SQL Editor.

create table if not exists public.mi_api_usage (
  usage_date date primary key default current_date,
  calls integer not null default 0,
  last_reason text,
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_fixtures (
  fixture_id bigint primary key,
  league_id integer,
  competition text,
  kickoff timestamptz,
  status text,
  minute integer,
  home_team_id bigint,
  home_team text,
  away_team_id bigint,
  away_team text,
  home_score integer,
  away_score integer,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create index if not exists mi_fixtures_kickoff_idx on public.mi_fixtures(kickoff);

create table if not exists public.mi_predictions (
  fixture_id bigint primary key,
  model_version text,
  stage text,
  lineup_confirmed boolean not null default false,
  payload jsonb not null default '{}'::jsonb,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_lineups (
  fixture_id bigint primary key,
  confirmed boolean not null default false,
  payload jsonb not null default '{}'::jsonb,
  checked_at timestamptz not null default now()
);

create table if not exists public.mi_live (
  fixture_id bigint primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_engine_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running',
  fixtures_seen integer not null default 0,
  lineups_checked integer not null default 0,
  live_checked integer not null default 0,
  predictions_run integer not null default 0,
  note text
);

create table if not exists public.mi_engine_lock (
  lock_name text primary key,
  locked_until timestamptz not null default '1970-01-01'::timestamptz,
  updated_at timestamptz not null default now()
);

create or replace function public.mi_consume_api_call(
  p_count integer,
  p_reason text,
  p_soft_cap integer default 6500,
  p_hard_cap integer default 7400,
  p_critical boolean default false
) returns jsonb
language plpgsql security definer set search_path=public as $$
declare
  v_calls integer;
begin
  insert into mi_api_usage(usage_date,calls,last_reason,updated_at)
  values(current_date,0,p_reason,now())
  on conflict (usage_date) do nothing;
  select calls into v_calls from mi_api_usage where usage_date=current_date for update;
  if v_calls + greatest(p_count,1) > p_hard_cap then
    return jsonb_build_object('allowed',false,'reason','Hard daily API reserve reached','calls',v_calls,'soft',p_soft_cap,'hard',p_hard_cap);
  end if;
  if not p_critical and v_calls + greatest(p_count,1) > p_soft_cap then
    return jsonb_build_object('allowed',false,'reason','Soft daily API cap reached; preserving live/XI reserve','calls',v_calls,'soft',p_soft_cap,'hard',p_hard_cap);
  end if;
  update mi_api_usage set calls=calls+greatest(p_count,1),last_reason=p_reason,updated_at=now() where usage_date=current_date returning calls into v_calls;
  return jsonb_build_object('allowed',true,'calls',v_calls,'remaining',p_hard_cap-v_calls,'soft',p_soft_cap,'hard',p_hard_cap);
end;$$;

create or replace function public.mi_try_engine_lock(p_seconds integer default 105)
returns boolean
language plpgsql security definer set search_path=public as $$
declare v_count integer:=0;
begin
  insert into mi_engine_lock(lock_name,locked_until,updated_at) values('main',now(),now()) on conflict(lock_name) do nothing;
  update mi_engine_lock set locked_until=now()+make_interval(secs=>greatest(30,p_seconds)),updated_at=now()
  where lock_name='main' and locked_until<=now();
  get diagnostics v_count = row_count;
  return v_count > 0;
end;$$;

alter table public.mi_api_usage enable row level security;
alter table public.mi_fixtures enable row level security;
alter table public.mi_predictions enable row level security;
alter table public.mi_lineups enable row level security;
alter table public.mi_live enable row level security;
alter table public.mi_engine_runs enable row level security;
alter table public.mi_engine_lock enable row level security;

revoke all on function public.mi_consume_api_call(integer,text,integer,integer,boolean) from public, anon, authenticated;
revoke all on function public.mi_try_engine_lock(integer) from public, anon, authenticated;
grant execute on function public.mi_consume_api_call(integer,text,integer,integer,boolean) to service_role;
grant execute on function public.mi_try_engine_lock(integer) to service_role;
