const {db,dbEnabled}=require('./_db.js');
const API='https://v3.football.api-sports.io';
const doneStatus=new Set(['FT','AET','PEN']);
const nowIso=()=>new Date().toISOString();
async function football(path){const key=process.env.API_FOOTBALL_KEY;if(!key)throw new Error('API_FOOTBALL_KEY missing');const r=await fetch(API+path,{headers:{'x-apisports-key':key}});if(!r.ok)throw new Error(`Football API ${r.status}`);return r.json()}
function statusCorrect(rule,h,a){const total=h+a;switch(rule){case'home0.5':return h>=1;case'away0.5':return a>=1;case'over1.5':return total>=2;case'over2.5':return total>=3;case'under3.5':return total<=3;case'under4.5':return total<=4;case'btts':return h>=1&&a>=1;case'homeOrDraw':return h>=a;case'awayOrDraw':return a>=h;case'homeWin':return h>a;case'draw':return h===a;case'awayWin':return a>h;default:return false}}
async function saveSnapshot(f,s){await db('mi_snapshots?on_conflict=fixture_id',{method:'POST',body:[{fixture_id:f.fixture_id,model:s.model,stage:s.stage,lineup_confirmed:!!s.lineupConfirmed,snapshot:s,updated_at:nowIso()}],prefer:'resolution=merge-duplicates,return=minimal'});if(s.stage!=='scout'){const rows=(s.predictions||[]).map(p=>({key:`${f.fixture_id}|${p.rule}|${s.model}|${s.stage}`,fixture_id:f.fixture_id,rule:p.rule,type:p.type,title:p.title,model:s.model,stage:s.stage,p:p.p,raw_p:p.rawP??p.p,lineup_confirmed:!!s.lineupConfirmed,kickoff:f.kickoff,engines:p.stats?.engineProbabilities||null,ablation:p.stats?.ablation||null}));if(rows.length)await db('mi_audit?on_conflict=key',{method:'POST',body:rows,prefer:'resolution=ignore-duplicates,return=minimal'})}}
async function settleFixture(f){const d=await football(`/fixtures?id=${encodeURIComponent(f.fixture_id)}`),x=d?.response?.[0];if(!x||!doneStatus.has(x?.fixture?.status?.short))return false;const h=Number(x?.goals?.home),a=Number(x?.goals?.away);if(!Number.isFinite(h)||!Number.isFinite(a))return false;const audits=await db(`mi_audit?fixture_id=eq.${encodeURIComponent(f.fixture_id)}&correct=is.null&select=key,rule`);for(const row of audits||[]){await db(`mi_audit?key=eq.${encodeURIComponent(row.key)}`,{method:'PATCH',body:{correct:statusCorrect(row.rule,h,a),result:`${h}-${a}`,settled_at:nowIso()},prefer:'return=minimal'})}await db(`mi_fixtures?fixture_id=eq.${encodeURIComponent(f.fixture_id)}`,{method:'PATCH',body:{status:x.fixture.status.short,goals_home:h,goals_away:a,last_checked_at:nowIso()},prefer:'return=minimal'});return true}
module.exports=async function handler(req,res){
 try{
  if(process.env.CRON_SECRET){const auth=req.headers.authorization||'';if(auth!==`Bearer ${process.env.CRON_SECRET}`)return res.status(401).json({error:'Unauthorized'})}
  if(!dbEnabled())return res.status(200).json({enabled:false,message:'Supabase not configured'});
  const now=Date.now(),from=new Date(now-4*3600e3).toISOString(),to=new Date(now+8*24*3600e3).toISOString();
  const fixtures=await db(`mi_fixtures?kickoff=gte.${encodeURIComponent(from)}&kickoff=lte.${encodeURIComponent(to)}&select=*&order=kickoff.asc&limit=240`)||[];
  const snaps=await db('mi_snapshots?select=fixture_id,snapshot,updated_at&limit=350')||[],snapMap=new Map(snaps.map(x=>[String(x.fixture_id),x]));let analysed=0,settled=0,skipped=0;
  const origin=`https://${process.env.VERCEL_URL||req.headers.host}`;
  for(const f of fixtures){const kick=new Date(f.kickoff).getTime(),mins=(kick-now)/60000,prev=snapMap.get(String(f.fixture_id))?.snapshot||null;if(mins<-90){if(await settleFixture(f).catch(()=>false))settled++;continue}if(mins<=0){skipped++;continue}let mode=null;if(!prev)mode=mins<24*60?'deep':'scout';else if(prev.lineupConfirmed){skipped++;continue}else if(mins<=75){const age=(now-Number(prev.ts||0))/60000;if(age>=8)mode='deep'}else if(prev.stage==='scout'&&Math.max(0,...(prev.predictions||[]).map(p=>p.p||0))>=70)mode='deep';else if((now-Number(prev.ts||0))>6*3600e3&&mins<24*60)mode='deep';if(!mode){skipped++;continue}
   const r=await fetch(origin+'/api/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fixtureId:f.fixture_id,homeTeam:f.home_team,awayTeam:f.away_team,homeTeamId:f.home_team_id,awayTeamId:f.away_team_id,competition:f.competition,fixtureDate:f.kickoff,leagueId:f.league_id,season:f.season,mode})});if(!r.ok)continue;const d=await r.json(),preds=d.predictions||[];let pre=prev?.preLineupProbabilities||null;if(d.lineupConfirmed&&!pre&&prev&&!prev.lineupConfirmed&&prev.stage!=='scout')pre=Object.fromEntries((prev.predictions||[]).map(x=>[x.rule,x.p]));if(pre)for(const p of preds){const before=Number(pre[p.rule]);if(Number.isFinite(before))p.stats={...(p.stats||{}),preLineupP:before,lineupDelta:p.p-before}}
   const stage=d.analysisStage||mode,ts=Date.now(),probabilityHistory=[...(prev?.probabilityHistory||[]),{ts,stage,probabilities:Object.fromEntries(preds.map(x=>[x.rule,x.p]))}].slice(-10);const snapshot={ts,model:d.model,stage,lineupConfirmed:!!d.lineupConfirmed,lineupChecked:!!d.lineupChecked,hasIntervening:!!d.hasIntervening,interveningUntil:d.interveningUntil||null,evidence:d.evidence||{},dataLayers:d.dataLayers||null,lineups:d.lineups||null,preLineupProbabilities:pre,probabilityHistory,predictions:preds};await saveSnapshot(f,snapshot);analysed++;if(analysed>=22)break;
  }
  return res.status(200).json({enabled:true,analysed,settled,skipped,checked:fixtures.length});
 }catch(e){return res.status(502).json({error:'Cron engine failed',detail:e?.message||String(e)})}
}
