const BASE='https://v3.football.api-sports.io';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const rows=d=>Array.isArray(d?.response)?d.response:[];
const LEAGUES={39:'Premier League',40:'Championship',41:'League One',42:'League Two'};
const cache=new Map();
async function api(path,key){const r=await fetch(BASE+path,{headers:{'x-apisports-key':key}});if(!r.ok)throw new Error(`API ${r.status}`);return r.json()}
async function mapLimit(items,n,fn){const out=[];let i=0;async function worker(){while(i<items.length){const x=items[i++];out.push(await fn(x).catch(()=>null))}}await Promise.all(Array.from({length:Math.min(n,items.length)},worker));return out.filter(Boolean)}
function seasonFor(){const d=new Date();return d.getUTCMonth()>=6?d.getUTCFullYear():d.getUTCFullYear()-1}
function role(pos){const p=String(pos||'').toLowerCase();if(p.includes('goal'))return'GK';if(p.includes('def'))return'DEF';if(p.includes('mid'))return'MID';return'ATT'}
function seasonScore(s){const rating=num(s.games?.rating,6.4),mins=num(s.games?.minutes),apps=num(s.games?.appearences),goals=num(s.goals?.total),assists=num(s.goals?.assists),clean=num(s.goals?.conceded===0&&role(s.games?.position)==='GK'?1:0);return clamp(50+(rating-6)*13+Math.log10(mins+10)*3+Math.min(8,goals*.7+assists*.5+clean),45,96)}
function recentMap(playerResponses){const m=new Map();for(const d of playerResponses){for(const team of rows(d)){for(const p of team.players||[]){const id=p?.player?.id;if(!id)continue;const stat=(p.statistics||[])[0]||{};const r=num(stat.games?.rating,null);if(r===null)continue;const cur=m.get(id)||{sum:0,n:0,mins:0};cur.sum+=r;cur.n++;cur.mins+=num(stat.games?.minutes);m.set(id,cur)}}}return m}
function scorePlayer(rec,mode){const season=rec.seasonScore,recent=rec.recentN?clamp(50+(rec.recentRating-6)*14,45,97):season,conf=clamp(45+Math.log10(rec.minutes+10)*18,45,96);if(mode==='season')return season;if(mode==='form')return rec.recentN>=2?recent*.88+season*.12:season*.75;return recent*.55+season*.35+conf*.10}
function chooseXI(players,mode){const scored=players.map(p=>({...p,score:+scorePlayer(p,mode).toFixed(1)})).sort((a,b)=>b.score-a.score);const gk=scored.filter(x=>x.role==='GK').slice(0,1),def=scored.filter(x=>x.role==='DEF').slice(0,4),mid=scored.filter(x=>x.role==='MID').slice(0,3),att=scored.filter(x=>x.role==='ATT').slice(0,3);const xi=[...gk,...def,...mid,...att];if(xi.length<11){const used=new Set(xi.map(x=>x.id));for(const p of scored){if(xi.length>=11)break;if(!used.has(p.id)){xi.push(p);used.add(p.id)}}}const strength=xi.length?xi.reduce((a,x)=>a+x.score,0)/xi.length:0;return{formation:'4-3-3',xi,strength}}
function assignGrid(xi){const shape={GK:[[1,1]],DEF:[[2,1],[2,2],[2,3],[2,4]],MID:[[3,1],[3,2],[3,3]],ATT:[[4,1],[4,2],[4,3]]};const idx={GK:0,DEF:0,MID:0,ATT:0};return xi.map(p=>({...p,grid:(shape[p.role]?.[idx[p.role]++]||[3,2]).join(':')}))}
module.exports=async function handler(req,res){try{const key=process.env.API_FOOTBALL_KEY;if(!key)return res.status(500).json({error:'API_FOOTBALL_KEY is not configured'});const league=Number(req.query.league||39),mode=['current','season','form'].includes(req.query.mode)?req.query.mode:'current',season=Number(req.query.season||seasonFor());if(!LEAGUES[league])return res.status(400).json({error:'League not supported'});const baseKey=`${league}|${season}`,hit=cache.get(baseKey);if(hit&&Date.now()-hit.ts<6*3600e3){const best=chooseXI(hit.pool,mode),xi=assignGrid(best.xi),data={league,leagueName:LEAGUES[league],season,mode,formation:best.formation,strength:+best.strength.toFixed(1),generatedAt:hit.generatedAt,samplePlayers:hit.pool.length,xi};res.setHeader('Cache-Control','s-maxage=21600, stale-while-revalidate=43200');return res.status(200).json(data)}
const pages=[];for(let p=1;p<=8;p++)pages.push(p);const playerPages=await mapLimit(pages,3,p=>api(`/players?league=${league}&season=${season}&page=${p}`,key));const pool=[];for(const d of playerPages){for(const r of rows(d)){const st=(r.statistics||[]).find(x=>x?.league?.id===league)||(r.statistics||[])[0]||{};if(!r?.player?.id||num(st.games?.minutes)<90)continue;pool.push({id:r.player.id,name:r.player.name,photo:r.player.photo||null,teamId:st.team?.id,team:st.team?.name||'',teamLogo:st.team?.logo||null,position:st.games?.position||r.player.position||'',role:role(st.games?.position||r.player.position),minutes:num(st.games?.minutes),appearances:num(st.games?.appearences),seasonRating:num(st.games?.rating,6.4),goals:num(st.goals?.total),assists:num(st.goals?.assists),seasonScore:seasonScore(st)})}}
const fx=await api(`/fixtures?league=${league}&season=${season}&last=24`,key).catch(()=>null);const playerResponses=fx?await mapLimit(rows(fx).map(x=>x.fixture.id),4,id=>api(`/fixtures/players?fixture=${id}`,key)):[];const recent=recentMap(playerResponses);for(const p of pool){const r=recent.get(p.id);p.recentRating=r?r.sum/r.n:null;p.recentN=r?.n||0;p.recentMinutes=r?.mins||0}const generatedAt=new Date().toISOString();cache.set(baseKey,{ts:Date.now(),pool,generatedAt});const best=chooseXI(pool,mode),xi=assignGrid(best.xi);const data={league,leagueName:LEAGUES[league],season,mode,formation:best.formation,strength:+best.strength.toFixed(1),generatedAt,samplePlayers:pool.length,xi};res.setHeader('Cache-Control','s-maxage=21600, stale-while-revalidate=43200');return res.status(200).json(data)}catch(e){return res.status(502).json({error:'League XI failed',detail:e?.message||String(e)})}}
